### ISSUE TITLE
运行问题

### ISSUE THREAD

**Issue by ChengHao565** [wangleiai/dVectorSpeakerRecognition#3]
dnnTran  51行
if x.shape!=(batchSize, x.shape[1], x.shape[2]):
IndexError: tuple index out of range

**Comment by wangleiai** [comment]
您在这行前面打印下x.shape看下吧吧，时间太长了，代码基本忘了。您最好在了解了思路后自己实现下，使用keras很快就可以复现了。非常不好意思给您带来麻烦。
